# Generated by Django 4.2.5 on 2023-10-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230909_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepage',
            name='is_for_specialization',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpecializationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('courses', models.ManyToManyField(to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='sharepage',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.specializationpage'),
        ),
    ]
